name: click_age
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  image_cropper: ^9.1.0
  shared_preferences: ^2.2.2
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.2
  path: ^1.9.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#EFE3D2"
  image: assets/images/logo.png
  fullscreen: true
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/my_image_1.jpg
